packages:
  - apps/*
  - packages/*
injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build
catalog:
  "@types/node": 24.13.3
  typescript: 6.0.3
  vitest: 4.1.10
allowBuilds:
  "@swc/core": true
  esbuild: true
  protobufjs: true
  unrs-resolver: false
minimumReleaseAgeExclude:
  - fastify@5.11.0
overrides:
  fast-xml-parser: 5.5.6
