packages:
  - apps/*
  - packages/*
injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build
catalog:
  "@types/node": 24.13.3
  typescript: 6.0.3
  vitest: 4.1.10
allowBuilds:
  esbuild: true
  unrs-resolver: false
minimumReleaseAgeExclude:
  - fastify@5.11.0
