import { readFile } from "node:fs/promises";

interface Registry {
  schemaVersion: number;
  owner: { team: string; contact: string };
  runbook: string;
  stores: readonly {
    name: string;
    class: string;
    retentionDays: number;
    exportHandler: string;
    deleteHandler: string;
  }[];
  indexes: readonly string[];
  caches: readonly string[];
}

export const REQUIRED_STORES = [
  "users",
  "workspaces",
  "memberships",
  "workflows",
  "workflow_versions",
  "workflow_nodes",
  "workflow_edges",
  "idempotency_records",
  "audit_events",
  "outbox_events",
  "knotline_schema_migrations",
  "identity_links",
  "magic_link_tokens",
  "identity_authorization_transactions",
  "identity_authorization_results",
  "sessions",
  "session_verifiers",
  "auth_rate_limits",
  "security_notifications",
  "auth_email_deliveries",
  "permission_catalog",
  "workspace_roles",
  "workspace_invitations",
  "workspace_groups",
  "workspace_group_memberships",
  "organization_relationships",
  "resource_grants",
  "onboarding_progress",
  "sandbox_resources",
  "guest_identities",
  "workflow_folders",
  "workflow_tags",
  "workflow_tag_assignments",
  "workflow_favorites",
  "workflow_validation_findings",
  "workflow_templates",
  "workflow_template_versions",
  "workflow_triggers",
  "workflow_generations",
  "workflow_test_runs",
  "generic_threads",
  "generic_comments",
  "comment_mentions",
  "comment_reactions",
  "resource_follows",
  "resource_activity_events",
  "notification_intents",
  "saved_resource_filters",
  "workflow_runs",
  "task_runs",
  "task_dependencies",
  "task_attempts",
  "run_events",
  "event_receipts",
  "external_operations",
  "external_operation_attempts",
  "external_operation_attempt_records",
  "dead_letter_items",
  "entitlement_policies",
  "billing_plan_versions",
  "billing_subscriptions",
  "billing_webhook_receipts",
  "budget_policies",
  "budget_thresholds",
  "usage_ledger",
  "billing_invoices",
  "service_principals",
  "api_credentials",
  "oauth_clients",
  "outgoing_webhooks",
  "outgoing_webhook_deliveries",
  "public_api_idempotency",
  "public_api_rate_buckets",
  "budget_periods",
  "admission_reservations",
  "admission_ledger_entries",
  "runtime_control_switches",
  "run_saved_views",
  "run_follows",
  "run_artifacts",
  "human_task_details",
  "human_task_drafts",
  "human_task_submissions",
  "task_delegations",
  "task_watchers",
  "task_queues",
  "task_queue_members",
  "task_routing_policy_versions",
  "task_routing_decisions",
  "business_calendars",
  "business_calendar_versions",
  "task_templates",
  "task_template_versions",
  "files",
  "file_versions",
  "file_upload_sessions",
  "task_file_attachments",
  "file_upload_parts",
  "file_derived_artifacts",
  "document_processing_jobs",
  "file_download_tokens",
  "file_usage_references",
  "file_deletion_tombstones",
  "workspace_storage_usage",
  "knowledge_index_generations",
  "knowledge_sources",
  "knowledge_document_sections",
  "knowledge_chunks",
  "knowledge_acl_projections",
  "knowledge_acl_members",
  "knowledge_authorization_proofs",
  "knowledge_retrieval_manifests",
  "knowledge_embedding_cache",
  "knowledge_embedding_usage",
  "knowledge_reindex_jobs",
  "knowledge_permission_invalidations",
  "knowledge_citation_accesses",
  "knowledge_type_versions",
  "knowledge_entities",
  "knowledge_entity_aliases",
  "knowledge_entity_facts",
  "knowledge_fact_evidence",
  "knowledge_relations",
  "knowledge_relation_evidence",
  "knowledge_entity_merge_candidates",
  "knowledge_entity_fact_conflicts",
  "knowledge_entity_changes",
  "knowledge_provenance_packets",
  "knowledge_graph_query_receipts",
  "knowledge_admin_actions",
  "connector_manifest_versions",
  "connections",
  "connection_authorization_transactions",
  "connection_scope_snapshots",
  "connection_sync_runs",
  "connection_sync_checkpoints",
  "connection_sync_pages",
  "connection_external_objects",
  "connector_webhook_endpoints",
  "provider_installation_bindings",
  "connector_webhook_receipts",
  "connector_reconciliations",
  "connector_control_switches",
  "connector_rate_buckets",
  "connection_source_selections",
  "provider_source_inventory",
  "provider_action_operations",
  "provider_action_receipts",
  "provider_connector_certifications",
  "collaboration_provider_accounts",
  "provider_metadata_snapshots",
  "provider_identity_bindings",
  "github_installation_binding_versions",
  "collaboration_action_policy_snapshots",
  "provider_webhook_quarantine",
  "connector_resource_grants",
  "connector_delta_cursors",
  "connector_import_batches",
  "connector_import_row_receipts",
  "generic_rest_spec_versions",
  "webhook_schema_versions",
  "webhook_delivery_receipts",
  "trigger_definition_versions",
  "trigger_schedules",
  "inbound_event_receipts",
  "trigger_source_checkpoints",
  "trigger_dispatch_queue",
  "trigger_health_snapshots",
  "captured_trigger_events",
  "outbound_sync_lineage",
  "notification_templates",
  "notification_template_versions",
  "notification_preferences",
  "notification_workspace_policies",
  "notification_items",
  "notification_deliveries",
  "notification_receipts",
  "notification_digests",
  "notification_suppressions",
  "notification_channel_installations",
  "search_documents",
  "recent_resources",
  "saved_views",
  "metric_definitions",
  "metric_buckets",
  "reports",
  "report_exports",
  "report_schedules",
  "product_analytics_events",
  "approval_policies",
  "approval_policy_versions",
  "approvals",
  "approval_steps",
  "approval_decisions",
  "approval_delegations",
  "sla_definitions",
  "sla_definition_versions",
  "sla_timer_events",
  "approval_consumptions",
  "agent_definitions",
  "agent_drafts",
  "agent_versions",
  "agent_release_channels",
  "agent_tags",
  "agent_tag_assignments",
  "agent_version_references",
  "agent_simulations",
  "reusable_schemas",
  "reusable_schema_versions",
  "agent_activity_events",
  "model_providers",
  "model_registry",
  "model_policies",
  "model_policy_versions",
  "prompt_versions",
  "model_invocations",
  "model_usage_charges",
  "provider_circuit_states",
  "tool_definitions",
  "tool_versions",
  "tool_grants",
  "credential_records",
  "oauth_refresh_leases",
  "tool_operation_bindings",
  "tool_execution_receipts",
  "sandbox_executions",
  "tool_control_switches",
  "agent_executions",
  "agent_execution_turns",
  "agent_context_manifests",
  "provenance_nodes",
  "provenance_edges",
  "memory_policies",
  "memory_records",
  "memory_versions",
  "memory_uses",
  "memory_tombstones",
  "evaluation_datasets",
  "evaluation_dataset_versions",
  "evaluation_cases",
  "evaluation_suites",
  "evaluation_runs",
  "evaluation_case_results",
  "evaluation_grader_results",
  "evaluation_comparisons",
  "evaluation_human_reviews",
  "agent_release_policies",
  "agent_releases",
  "agent_release_allocations",
  "agent_online_metric_buckets",
  "scheduled_evaluations"
] as const;

export async function validateDataStoreRegistry(): Promise<Registry> {
  const registry = JSON.parse(
    await readFile(new URL("../registry/data-stores.json", import.meta.url), "utf8")
  ) as Registry;
  const errors: string[] = [];
  if (registry.schemaVersion !== 1) errors.push("schemaVersion must be 1");
  if (!registry.owner.team || !registry.owner.contact) errors.push("owner is required");
  if (!registry.runbook.startsWith("docs/operations/knotline/")) errors.push("runbook is invalid");
  const names = new Set(registry.stores.map(({ name }) => name));
  for (const required of REQUIRED_STORES)
    if (!names.has(required)) errors.push(`missing ${required}`);
  for (const store of registry.stores) {
    if (!store.class.includes(".")) errors.push(`${store.name} has invalid class`);
    if (!Number.isInteger(store.retentionDays) || store.retentionDays < 0)
      errors.push(`${store.name} has invalid retention`);
    if (!store.exportHandler || !store.deleteHandler)
      errors.push(`${store.name} has no export/delete handler`);
  }
  if (new Set(registry.indexes).size !== registry.indexes.length) errors.push("duplicate index");
  if (errors.length > 0) throw new Error(`Invalid data-store registry:\n- ${errors.join("\n- ")}`);
  return registry;
}
