/* eslint-disable knotline/no-hardcoded-user-visible-string -- This operational surface now renders server-authored task data; localization follows the verified vertical journey. */
import { Badge, Button, Card, ErrorState, Skeleton } from "@knotline/ui";
import { CheckCircle2, Clock3, Inbox, Search } from "lucide-react";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Link, useParams, useSearchParams } from "react-router-dom";

import { fetchHumanTask, fetchHumanTasks, submitHumanTask } from "./api.js";
import "./M12Pages.css";

type TaskView = Readonly<Record<string, unknown>>;

function TaskShell({ children }: { readonly children: React.ReactNode }) {
  return (
    <div className="task-shell">
      <aside aria-label="Task navigation">
        <Link className="task-brand" to="/app/workflows">
          Knotline
        </Link>
        <Link to="/app/inbox" aria-current="page">
          <Inbox aria-hidden="true" /> Inbox
        </Link>
        <Link to="/app/approvals">
          <CheckCircle2 aria-hidden="true" /> Approvals
        </Link>
        <Link to="/app/runs">
          <Clock3 aria-hidden="true" /> Runs
        </Link>
      </aside>
      <main>{children}</main>
    </div>
  );
}

const label = (value: unknown) =>
  (typeof value === "string" || typeof value === "number" ? String(value) : "").replaceAll(
    "_",
    " "
  );

export function TaskInboxPage() {
  const [search, setSearch] = useSearchParams();
  const [tasks, setTasks] = useState<readonly TaskView[]>();
  const [error, setError] = useState<Error>();
  const query = search.get("query") ?? "";
  const view = search.get("view") ?? "all";
  useEffect(() => {
    void fetchHumanTasks(view)
      .then(setTasks)
      .catch((cause: unknown) =>
        setError(cause instanceof Error ? cause : new Error("Unable to load human work."))
      );
  }, [view]);
  const visible = useMemo(
    () =>
      (tasks ?? []).filter((task) =>
        label(task.node_key).toLowerCase().includes(query.toLowerCase())
      ),
    [query, tasks]
  );
  const update = (key: string, value: string) => {
    const next = new URLSearchParams(search);
    if (value) next.set(key, value);
    else next.delete(key);
    setSearch(next, { replace: true });
  };
  return (
    <TaskShell>
      <header className="task-page-header">
        <div>
          <Badge tone="accent">Persisted workspace queue</Badge>
          <h1>Inbox</h1>
          <p>Human tasks generated by durable workflow runs.</p>
        </div>
      </header>
      <nav className="task-tabs" aria-label="Inbox views">
        {(
          [
            ["all", "All work"],
            ["mine", "My work"],
            ["unassigned", "Unassigned"],
            ["completed", "Completed"]
          ] as const
        ).map(([key, text]) => (
          <button key={key} aria-pressed={view === key} onClick={() => update("view", key)}>
            {text}
          </button>
        ))}
      </nav>
      <section className="task-filters" aria-label="Task filters">
        <label>
          <span>Search tasks</span>
          <div>
            <Search aria-hidden="true" />
            <input value={query} onChange={(event) => update("query", event.currentTarget.value)} />
          </div>
        </label>
      </section>
      {error ? (
        <ErrorState title="Inbox unavailable">
          <p>{error.message}</p>
        </ErrorState>
      ) : !tasks ? (
        <Skeleton label="Loading human tasks" />
      ) : visible.length === 0 ? (
        <Card>
          <h2>No human work in this view</h2>
          <p>
            Start the launch workflow; its final publication step will appear here after approval.
          </p>
          <Link to="/app/workflows">Open workflows</Link>
        </Card>
      ) : (
        <ul className="task-list">
          {visible.map((task) => (
            <li key={String(task.id)}>
              <Link to={`/app/tasks/${String(task.id)}`}>
                <span
                  className={`task-priority task-priority--${label(task.priority) || "normal"}`}
                />
                <div>
                  <strong>{label(task.node_key)}</strong>
                  <small>Run {String(task.run_id)}</small>
                </div>
                <Badge
                  tone={
                    task.state === "ready"
                      ? "warning"
                      : task.state === "succeeded"
                        ? "success"
                        : "neutral"
                  }
                >
                  {label(task.state)}
                </Badge>
                <span>{label(task.priority)}</span>
              </Link>
            </li>
          ))}
        </ul>
      )}
    </TaskShell>
  );
}

export function TaskDetailPage() {
  const { taskRunId = "" } = useParams();
  const [task, setTask] = useState<TaskView>();
  const [error, setError] = useState<Error>();
  const [busy, setBusy] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  useEffect(() => {
    void fetchHumanTask(taskRunId)
      .then(setTask)
      .catch((cause: unknown) =>
        setError(cause instanceof Error ? cause : new Error("Unable to load task."))
      );
  }, [taskRunId]);
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!task) return;
    const form = new FormData(event.currentTarget);
    const publicationNote = form.get("publication_note");
    setBusy(true);
    try {
      await submitHumanTask(taskRunId, Number(task.state_version), {
        publication_note: typeof publicationNote === "string" ? publicationNote : ""
      });
      setSubmitted(true);
      setTask(await fetchHumanTask(taskRunId));
    } catch (cause) {
      setError(cause instanceof Error ? cause : new Error("The task could not be submitted."));
    } finally {
      setBusy(false);
    }
  };
  if (error)
    return (
      <TaskShell>
        <ErrorState title="Task unavailable">
          <p>{error.message}</p>
        </ErrorState>
      </TaskShell>
    );
  if (!task)
    return (
      <TaskShell>
        <Skeleton label="Loading human task" />
      </TaskShell>
    );
  if (submitted || task.state === "succeeded")
    return (
      <TaskShell>
        <section className="task-complete">
          <CheckCircle2 aria-hidden="true" />
          <h1>Task submitted</h1>
          <p>The immutable response was recorded and the durable workflow resumed.</p>
          <Link to={`/app/runs/${String(task.run_id)}`}>Return to the live run</Link>
        </section>
      </TaskShell>
    );
  const ready = ["ready", "running", "waiting"].includes(String(task.state));
  return (
    <TaskShell>
      <header className="task-detail-header">
        <div>
          <Link to="/app/inbox">← Inbox</Link>
          <h1>{label(task.node_key)}</h1>
          <p>
            Run {String(task.run_id)} · task {taskRunId}
          </p>
        </div>
        <div>
          <Badge tone={ready ? "warning" : "neutral"}>{label(task.state)}</Badge>
        </div>
      </header>
      <div className="task-detail-grid">
        <form className="task-form" onSubmit={(event) => void submit(event)}>
          <div className="task-form-status">
            <strong>Publication confirmation</strong>
            <span>Submission is immutable.</span>
          </div>
          <label className="human-field">
            <span>Publication note</span>
            <textarea
              name="publication_note"
              required
              rows={8}
              defaultValue="Approved launch brief reviewed. Publish to the product, sales, and customer operations audience."
            />
          </label>
          <footer>
            <span>This completes the final human node.</span>
            <Button tone="accent" type="submit" disabled={busy || !ready}>
              {busy ? "Submitting…" : "Submit and complete run"}
            </Button>
          </footer>
        </form>
        <aside className="task-context">
          <Card>
            <h2>Workflow context</h2>
            <p>
              This task became ready only after the governed agent completed and leadership approved
              the exact launch payload.
            </p>
            <Link to={`/app/runs/${String(task.run_id)}`}>Open run room</Link>
          </Card>
          <Card>
            <h2>Assignment</h2>
            <p>Priority: {label(task.priority)}</p>
            <p>State version: {String(task.state_version)}</p>
          </Card>
        </aside>
      </div>
    </TaskShell>
  );
}
