// Generated by tooling/quality/plan-contract.mjs. Do not edit.
export const canonicalWebRoutes = [
  {
    "id": "route.public.home",
    "path": "/",
    "requiredSurface": "Product narrative, interactive example, use cases, proof, CTA",
    "sourceSection": "5.1",
    "routeClass": "static_public",
    "ownerMilestone": "M02",
    "journeyIds": [
      "CJ-01"
    ]
  },
  {
    "id": "route.accessibility",
    "path": "/accessibility",
    "requiredSurface": "Current accessibility statement and contact path",
    "sourceSection": "5.1",
    "routeClass": "static_public",
    "ownerMilestone": "M33",
    "journeyIds": [
      "CJ-01"
    ]
  },
  {
    "id": "route.app",
    "path": "/app",
    "requiredSurface": "Role-aware operations home",
    "sourceSection": "5.2",
    "routeClass": "protected_collection",
    "ownerMilestone": "M28",
    "journeyIds": [
      "CJ-16"
    ]
  },
  {
    "id": "route.app.agents",
    "path": "/app/agents",
    "requiredSurface": "Agent catalog, status, health, usage",
    "sourceSection": "5.5",
    "routeClass": "protected_collection",
    "ownerMilestone": "M14",
    "journeyIds": [
      "CJ-10"
    ]
  },
  {
    "id": "route.app.agents.detail",
    "path": "/app/agents/:agentId",
    "requiredSurface": "Definition overview and versions",
    "sourceSection": "5.5",
    "routeClass": "protected_detail",
    "ownerMilestone": "M14",
    "journeyIds": [
      "CJ-10"
    ]
  },
  {
    "id": "route.app.agents.detail.activity",
    "path": "/app/agents/:agentId/activity",
    "requiredSurface": "Invocations, quality, latency, cost, failures",
    "sourceSection": "5.5",
    "routeClass": "protected_detail",
    "ownerMilestone": "M18",
    "journeyIds": [
      "CJ-10"
    ]
  },
  {
    "id": "route.app.agents.detail.builder",
    "path": "/app/agents/:agentId/builder",
    "requiredSurface": "Instructions, schemas, model, retrieval, tools, budgets",
    "sourceSection": "5.5",
    "routeClass": "protected_detail",
    "ownerMilestone": "M14",
    "journeyIds": [
      "CJ-10"
    ]
  },
  {
    "id": "route.app.agents.detail.evals",
    "path": "/app/agents/:agentId/evals",
    "requiredSurface": "Datasets, runs, comparisons, release gates",
    "sourceSection": "5.5",
    "routeClass": "protected_detail",
    "ownerMilestone": "M18",
    "journeyIds": [
      "CJ-10"
    ]
  },
  {
    "id": "route.app.agents.detail.memory",
    "path": "/app/agents/:agentId/memory",
    "requiredSurface": "Permitted memory policies, records, uses, and workspace-shared administration",
    "sourceSection": "5.5",
    "routeClass": "protected_detail",
    "ownerMilestone": "M17",
    "journeyIds": [
      "CJ-11"
    ]
  },
  {
    "id": "route.app.agents.new",
    "path": "/app/agents/new",
    "requiredSurface": "Guided agent creation",
    "sourceSection": "5.5",
    "routeClass": "editor_form_settings",
    "ownerMilestone": "M14",
    "journeyIds": [
      "CJ-10"
    ]
  },
  {
    "id": "route.app.analytics",
    "path": "/app/analytics",
    "requiredSurface": "Operational analytics",
    "sourceSection": "5.6",
    "routeClass": "protected_collection",
    "ownerMilestone": "M28",
    "journeyIds": [
      "CJ-16"
    ]
  },
  {
    "id": "route.app.analytics.reports.detail",
    "path": "/app/analytics/reports/:reportId",
    "requiredSurface": "Report detail and export",
    "sourceSection": "5.6",
    "routeClass": "protected_detail",
    "ownerMilestone": "M28",
    "journeyIds": [
      "CJ-16"
    ]
  },
  {
    "id": "route.app.approvals",
    "path": "/app/approvals",
    "requiredSurface": "Approval queue",
    "sourceSection": "5.4",
    "routeClass": "live_operator",
    "ownerMilestone": "M13",
    "journeyIds": [
      "CJ-09"
    ]
  },
  {
    "id": "route.app.approvals.detail",
    "path": "/app/approvals/:approvalId",
    "requiredSurface": "Exact payload, policy, evidence, decision",
    "sourceSection": "5.4",
    "routeClass": "live_operator",
    "ownerMilestone": "M13",
    "journeyIds": [
      "CJ-09"
    ]
  },
  {
    "id": "route.app.connections",
    "path": "/app/connections",
    "requiredSurface": "Integration catalog and connected accounts",
    "sourceSection": "5.6",
    "routeClass": "protected_collection",
    "ownerMilestone": "M22",
    "journeyIds": [
      "CJ-13.FRAMEWORK"
    ]
  },
  {
    "id": "route.app.connections.detail",
    "path": "/app/connections/:integrationId",
    "requiredSurface": "Health, scopes, syncs, webhooks, actions",
    "sourceSection": "5.6",
    "routeClass": "protected_detail",
    "ownerMilestone": "M22",
    "journeyIds": [
      "CJ-13.FRAMEWORK"
    ]
  },
  {
    "id": "route.app.connections.new.detail",
    "path": "/app/connections/new/:provider",
    "requiredSurface": "Authorization/setup",
    "sourceSection": "5.6",
    "routeClass": "editor_form_settings",
    "ownerMilestone": "M22",
    "journeyIds": [
      "CJ-13.FRAMEWORK"
    ]
  },
  {
    "id": "route.app.developer.api",
    "path": "/app/developer/api",
    "requiredSurface": "Interactive workspace API documentation",
    "sourceSection": "5.6",
    "routeClass": "protected_collection",
    "ownerMilestone": "M30",
    "journeyIds": [
      "CJ-18"
    ]
  },
  {
    "id": "route.app.developer.apps",
    "path": "/app/developer/apps",
    "requiredSurface": "OAuth clients, credentials, scopes, and consent configuration",
    "sourceSection": "5.6",
    "routeClass": "protected_collection",
    "ownerMilestone": "M30",
    "journeyIds": [
      "CJ-18"
    ]
  },
  {
    "id": "route.app.developer.webhooks",
    "path": "/app/developer/webhooks",
    "requiredSurface": "Public webhook subscriptions, tests, logs, and redelivery",
    "sourceSection": "5.6",
    "routeClass": "protected_collection",
    "ownerMilestone": "M30",
    "journeyIds": [
      "CJ-18"
    ]
  },
  {
    "id": "route.app.feedback",
    "path": "/app/feedback",
    "requiredSurface": "Product, citation-quality, accessibility, and unsafe-output report",
    "sourceSection": "5.2",
    "routeClass": "protected_collection",
    "ownerMilestone": "M33",
    "journeyIds": [
      "CJ-22"
    ]
  },
  {
    "id": "route.app.inbox",
    "path": "/app/inbox",
    "requiredSurface": "Unified tasks, approvals, mentions, and exceptions",
    "sourceSection": "5.2",
    "routeClass": "protected_collection",
    "ownerMilestone": "M12",
    "journeyIds": [
      "CJ-08",
      "CJ-09"
    ]
  },
  {
    "id": "route.app.knowledge",
    "path": "/app/knowledge",
    "requiredSurface": "Source and corpus overview",
    "sourceSection": "5.5",
    "routeClass": "protected_collection",
    "ownerMilestone": "M21",
    "journeyIds": [
      "CJ-12"
    ]
  },
  {
    "id": "route.app.knowledge.documents.detail",
    "path": "/app/knowledge/documents/:documentId",
    "requiredSurface": "Versions, parse, permissions, citations",
    "sourceSection": "5.5",
    "routeClass": "protected_detail",
    "ownerMilestone": "M19",
    "journeyIds": [
      "CJ-12"
    ]
  },
  {
    "id": "route.app.knowledge.entities",
    "path": "/app/knowledge/entities",
    "requiredSurface": "Entity explorer",
    "sourceSection": "5.5",
    "routeClass": "protected_collection",
    "ownerMilestone": "M21",
    "journeyIds": [
      "CJ-12"
    ]
  },
  {
    "id": "route.app.knowledge.entities.detail",
    "path": "/app/knowledge/entities/:entityId",
    "requiredSurface": "Attributes, relations, provenance",
    "sourceSection": "5.5",
    "routeClass": "protected_detail",
    "ownerMilestone": "M21",
    "journeyIds": [
      "CJ-12"
    ]
  },
  {
    "id": "route.app.knowledge.search",
    "path": "/app/knowledge/search",
    "requiredSurface": "Hybrid search debugger",
    "sourceSection": "5.5",
    "routeClass": "protected_collection",
    "ownerMilestone": "M20",
    "journeyIds": [
      "CJ-12"
    ]
  },
  {
    "id": "route.app.knowledge.sources",
    "path": "/app/knowledge/sources",
    "requiredSurface": "Files and connected sources",
    "sourceSection": "5.5",
    "routeClass": "protected_collection",
    "ownerMilestone": "M19",
    "journeyIds": [
      "CJ-12"
    ]
  },
  {
    "id": "route.app.notifications",
    "path": "/app/notifications",
    "requiredSurface": "Notification center",
    "sourceSection": "5.2",
    "routeClass": "protected_collection",
    "ownerMilestone": "M27",
    "journeyIds": [
      "CJ-15"
    ]
  },
  {
    "id": "route.app.onboarding",
    "path": "/app/onboarding",
    "requiredSurface": "Resumable activation flow",
    "sourceSection": "5.2",
    "routeClass": "protected_collection",
    "ownerMilestone": "M05",
    "journeyIds": [
      "CJ-03"
    ]
  },
  {
    "id": "route.app.profile",
    "path": "/app/profile",
    "requiredSurface": "Profile, locale, accessibility, and notification preferences",
    "sourceSection": "5.2",
    "routeClass": "protected_collection",
    "ownerMilestone": "M04",
    "journeyIds": [
      "CJ-02"
    ]
  },
  {
    "id": "route.app.profile.memory",
    "path": "/app/profile/memory",
    "requiredSurface": "User-private agent memory, provenance, correction, export, and deletion",
    "sourceSection": "5.2",
    "routeClass": "protected_collection",
    "ownerMilestone": "M17",
    "journeyIds": [
      "CJ-11"
    ]
  },
  {
    "id": "route.app.profile.sessions",
    "path": "/app/profile/sessions",
    "requiredSurface": "Session inventory and revocation",
    "sourceSection": "5.2",
    "routeClass": "protected_collection",
    "ownerMilestone": "M04",
    "journeyIds": [
      "CJ-02"
    ]
  },
  {
    "id": "route.app.runs",
    "path": "/app/runs",
    "requiredSurface": "Filterable run operations table",
    "sourceSection": "5.4",
    "routeClass": "live_operator",
    "ownerMilestone": "M11",
    "journeyIds": [
      "CJ-07"
    ]
  },
  {
    "id": "route.app.runs.detail",
    "path": "/app/runs/:runId",
    "requiredSurface": "Live run room",
    "sourceSection": "5.4",
    "routeClass": "live_operator",
    "ownerMilestone": "M11",
    "journeyIds": [
      "CJ-07"
    ]
  },
  {
    "id": "route.app.runs.detail.tasks.detail",
    "path": "/app/runs/:runId/tasks/:taskRunId",
    "requiredSurface": "Task, attempts, inputs, outputs, provenance",
    "sourceSection": "5.4",
    "routeClass": "live_operator",
    "ownerMilestone": "M11",
    "journeyIds": [
      "CJ-07"
    ]
  },
  {
    "id": "route.app.runs.detail.timeline",
    "path": "/app/runs/:runId/timeline",
    "requiredSurface": "Complete sequenced history",
    "sourceSection": "5.4",
    "routeClass": "live_operator",
    "ownerMilestone": "M11",
    "journeyIds": [
      "CJ-07"
    ]
  },
  {
    "id": "route.app.search",
    "path": "/app/search",
    "requiredSurface": "Permission-aware global search",
    "sourceSection": "5.2",
    "routeClass": "protected_collection",
    "ownerMilestone": "M28",
    "journeyIds": [
      "CJ-16"
    ]
  },
  {
    "id": "route.app.settings.audit",
    "path": "/app/settings/audit",
    "requiredSurface": "Audit explorer and exports",
    "sourceSection": "5.6",
    "routeClass": "editor_form_settings",
    "ownerMilestone": "M31",
    "journeyIds": [
      "CJ-19"
    ]
  },
  {
    "id": "route.app.settings.billing",
    "path": "/app/settings/billing",
    "requiredSurface": "Plan, payment, usage, invoices",
    "sourceSection": "5.6",
    "routeClass": "editor_form_settings",
    "ownerMilestone": "M29",
    "journeyIds": [
      "CJ-17"
    ]
  },
  {
    "id": "route.app.settings.data",
    "path": "/app/settings/data",
    "requiredSurface": "Retention, export, deletion, residency",
    "sourceSection": "5.6",
    "routeClass": "editor_form_settings",
    "ownerMilestone": "M31",
    "journeyIds": [
      "CJ-19"
    ]
  },
  {
    "id": "route.app.settings.developers",
    "path": "/app/settings/developers",
    "requiredSurface": "Service principals, API credentials, OAuth clients",
    "sourceSection": "5.6",
    "routeClass": "editor_form_settings",
    "ownerMilestone": "M30",
    "journeyIds": [
      "CJ-18"
    ]
  },
  {
    "id": "route.app.settings.feature-access",
    "path": "/app/settings/feature-access",
    "requiredSurface": "Connector/model/agent allowlists and kill switches",
    "sourceSection": "5.6",
    "routeClass": "editor_form_settings",
    "ownerMilestone": "M34",
    "journeyIds": [
      "CJ-23"
    ]
  },
  {
    "id": "route.app.settings.identity",
    "path": "/app/settings/identity",
    "requiredSurface": "SSO, domains, SCIM, JIT, and enterprise sessions",
    "sourceSection": "5.6",
    "routeClass": "editor_form_settings",
    "ownerMilestone": "M32",
    "journeyIds": [
      "CJ-04"
    ]
  },
  {
    "id": "route.app.settings.members",
    "path": "/app/settings/members",
    "requiredSurface": "Members, invitations, groups",
    "sourceSection": "5.6",
    "routeClass": "editor_form_settings",
    "ownerMilestone": "M05",
    "journeyIds": [
      "CJ-03"
    ]
  },
  {
    "id": "route.app.settings.notifications",
    "path": "/app/settings/notifications",
    "requiredSurface": "Workspace notification and escalation defaults",
    "sourceSection": "5.6",
    "routeClass": "editor_form_settings",
    "ownerMilestone": "M27",
    "journeyIds": [
      "CJ-15"
    ]
  },
  {
    "id": "route.app.settings.policies",
    "path": "/app/settings/policies",
    "requiredSurface": "Model, connector, memory, sharing, telemetry, and support policies",
    "sourceSection": "5.6",
    "routeClass": "editor_form_settings",
    "ownerMilestone": "M32",
    "journeyIds": [
      "CJ-04",
      "CJ-19.REGION_MIGRATION"
    ]
  },
  {
    "id": "route.app.settings.roles",
    "path": "/app/settings/roles",
    "requiredSurface": "System and custom roles",
    "sourceSection": "5.6",
    "routeClass": "editor_form_settings",
    "ownerMilestone": "M05",
    "journeyIds": [
      "CJ-03"
    ]
  },
  {
    "id": "route.app.settings.security",
    "path": "/app/settings/security",
    "requiredSurface": "Sessions, domains, SSO, SCIM, policies",
    "sourceSection": "5.6",
    "routeClass": "editor_form_settings",
    "ownerMilestone": "M32",
    "journeyIds": [
      "CJ-04"
    ]
  },
  {
    "id": "route.app.settings.support-access",
    "path": "/app/settings/support-access",
    "requiredSurface": "Customer-authorized and emergency support access history",
    "sourceSection": "5.6",
    "routeClass": "editor_form_settings",
    "ownerMilestone": "M31",
    "journeyIds": [
      "CJ-19"
    ]
  },
  {
    "id": "route.app.settings.usage",
    "path": "/app/settings/usage",
    "requiredSurface": "Meter and cost explorer",
    "sourceSection": "5.6",
    "routeClass": "editor_form_settings",
    "ownerMilestone": "M29",
    "journeyIds": [
      "CJ-17"
    ]
  },
  {
    "id": "route.app.settings.webhooks",
    "path": "/app/settings/webhooks",
    "requiredSurface": "Outgoing webhooks and delivery logs",
    "sourceSection": "5.6",
    "routeClass": "editor_form_settings",
    "ownerMilestone": "M30",
    "journeyIds": [
      "CJ-18"
    ]
  },
  {
    "id": "route.app.settings.workspace",
    "path": "/app/settings/workspace",
    "requiredSurface": "Name, region, defaults",
    "sourceSection": "5.6",
    "routeClass": "editor_form_settings",
    "ownerMilestone": "M05",
    "journeyIds": [
      "CJ-03"
    ]
  },
  {
    "id": "route.app.support",
    "path": "/app/support",
    "requiredSurface": "Support cases, service targets, status, and new request",
    "sourceSection": "5.2",
    "routeClass": "protected_collection",
    "ownerMilestone": "M33",
    "journeyIds": [
      "CJ-22"
    ]
  },
  {
    "id": "route.app.support.detail",
    "path": "/app/support/:ticketId",
    "requiredSurface": "Ticket messages, attachments, diagnostics, and resolution",
    "sourceSection": "5.2",
    "routeClass": "protected_detail",
    "ownerMilestone": "M33",
    "journeyIds": [
      "CJ-22"
    ]
  },
  {
    "id": "route.app.tasks",
    "path": "/app/tasks",
    "requiredSurface": "Human task list and saved views",
    "sourceSection": "5.4",
    "routeClass": "live_operator",
    "ownerMilestone": "M12",
    "journeyIds": [
      "CJ-08"
    ]
  },
  {
    "id": "route.app.tasks.detail",
    "path": "/app/tasks/:taskRunId",
    "requiredSurface": "Task form, context, comments, artifacts",
    "sourceSection": "5.4",
    "routeClass": "live_operator",
    "ownerMilestone": "M12",
    "journeyIds": [
      "CJ-08"
    ]
  },
  {
    "id": "route.app.templates",
    "path": "/app/templates",
    "requiredSurface": "Workspace and first-party templates",
    "sourceSection": "5.3",
    "routeClass": "protected_collection",
    "ownerMilestone": "M06",
    "journeyIds": [
      "CJ-05"
    ]
  },
  {
    "id": "route.app.templates.detail",
    "path": "/app/templates/:templateId",
    "requiredSurface": "Template editor, versions, usage",
    "sourceSection": "5.3",
    "routeClass": "protected_detail",
    "ownerMilestone": "M06",
    "journeyIds": [
      "CJ-05"
    ]
  },
  {
    "id": "route.app.workflows",
    "path": "/app/workflows",
    "requiredSurface": "Library, folders, tags, filters, bulk actions",
    "sourceSection": "5.3",
    "routeClass": "protected_collection",
    "ownerMilestone": "M06",
    "journeyIds": [
      "CJ-05"
    ]
  },
  {
    "id": "route.app.workflows.detail",
    "path": "/app/workflows/:workflowId",
    "requiredSurface": "Overview, health, versions, runs",
    "sourceSection": "5.3",
    "routeClass": "protected_detail",
    "ownerMilestone": "M06",
    "journeyIds": [
      "CJ-05"
    ]
  },
  {
    "id": "route.app.workflows.detail.settings",
    "path": "/app/workflows/:workflowId/settings",
    "requiredSurface": "Ownership, permissions, retention, archive/delete",
    "sourceSection": "5.3",
    "routeClass": "editor_form_settings",
    "ownerMilestone": "M06",
    "journeyIds": [
      "CJ-05"
    ]
  },
  {
    "id": "route.app.workflows.detail.studio",
    "path": "/app/workflows/:workflowId/studio",
    "requiredSurface": "Graph editor and accessible outline",
    "sourceSection": "5.3",
    "routeClass": "editor_form_settings",
    "ownerMilestone": "M07",
    "journeyIds": [
      "CJ-05"
    ]
  },
  {
    "id": "route.app.workflows.detail.triggers",
    "path": "/app/workflows/:workflowId/triggers",
    "requiredSurface": "Manual, schedule, webhook, event, API triggers",
    "sourceSection": "5.3",
    "routeClass": "protected_detail",
    "ownerMilestone": "M26",
    "journeyIds": [
      "CJ-14"
    ]
  },
  {
    "id": "route.app.workflows.detail.versions",
    "path": "/app/workflows/:workflowId/versions",
    "requiredSurface": "Immutable version history",
    "sourceSection": "5.3",
    "routeClass": "protected_detail",
    "ownerMilestone": "M06",
    "journeyIds": [
      "CJ-05"
    ]
  },
  {
    "id": "route.app.workflows.detail.versions.detail",
    "path": "/app/workflows/:workflowId/versions/:version",
    "requiredSurface": "Read-only version and diff entry",
    "sourceSection": "5.3",
    "routeClass": "protected_detail",
    "ownerMilestone": "M06",
    "journeyIds": [
      "CJ-05"
    ]
  },
  {
    "id": "route.app.workflows.new",
    "path": "/app/workflows/new",
    "requiredSurface": "Blank, prompt, import, or template creation",
    "sourceSection": "5.3",
    "routeClass": "editor_form_settings",
    "ownerMilestone": "M08",
    "journeyIds": [
      "CJ-06"
    ]
  },
  {
    "id": "route.auth.check-email",
    "path": "/auth/check-email",
    "requiredSurface": "Non-enumerating email confirmation",
    "sourceSection": "5.1",
    "routeClass": "public_async",
    "ownerMilestone": "M04",
    "journeyIds": [
      "CJ-02"
    ]
  },
  {
    "id": "route.auth.google.callback",
    "path": "/auth/google/callback",
    "requiredSurface": "OIDC callback and clean redirect",
    "sourceSection": "5.1",
    "routeClass": "public_async",
    "ownerMilestone": "M04",
    "journeyIds": [
      "CJ-02"
    ]
  },
  {
    "id": "route.auth.magic.callback",
    "path": "/auth/magic/callback",
    "requiredSurface": "One-time exchange and clean redirect",
    "sourceSection": "5.1",
    "routeClass": "public_async",
    "ownerMilestone": "M04",
    "journeyIds": [
      "CJ-02"
    ]
  },
  {
    "id": "route.auth.sign-in",
    "path": "/auth/sign-in",
    "requiredSurface": "Magic-link and Google sign-in",
    "sourceSection": "5.1",
    "routeClass": "public_async",
    "ownerMilestone": "M04",
    "journeyIds": [
      "CJ-02"
    ]
  },
  {
    "id": "route.changelog",
    "path": "/changelog",
    "requiredSurface": "Versioned product changes",
    "sourceSection": "5.1",
    "routeClass": "static_public",
    "ownerMilestone": "M02",
    "journeyIds": [
      "CJ-01"
    ]
  },
  {
    "id": "route.contact",
    "path": "/contact",
    "requiredSurface": "Sales/contact workflow",
    "sourceSection": "5.1",
    "routeClass": "editor_form_settings",
    "ownerMilestone": "M33",
    "journeyIds": [
      "CJ-01"
    ]
  },
  {
    "id": "route.docs",
    "path": "/docs",
    "requiredSurface": "Product and API documentation home",
    "sourceSection": "5.1",
    "routeClass": "public_async",
    "ownerMilestone": "M02",
    "journeyIds": [
      "CJ-01"
    ]
  },
  {
    "id": "route.docs.wildcard",
    "path": "/docs/*",
    "requiredSurface": "Searchable documentation pages",
    "sourceSection": "5.1",
    "routeClass": "public_async",
    "ownerMilestone": "M02",
    "journeyIds": [
      "CJ-01"
    ]
  },
  {
    "id": "route.guest",
    "path": "/guest",
    "requiredSurface": "Asset-isolated scoped guest-token exchange followed by task, approval, or resource surface",
    "sourceSection": "5.1",
    "routeClass": "public_async",
    "ownerMilestone": "M33",
    "journeyIds": [
      "CJ-20"
    ]
  },
  {
    "id": "route.help",
    "path": "/help",
    "requiredSurface": "Versioned product help, troubleshooting, and support entry",
    "sourceSection": "5.1",
    "routeClass": "public_async",
    "ownerMilestone": "M33",
    "journeyIds": [
      "CJ-22"
    ]
  },
  {
    "id": "route.help.wildcard",
    "path": "/help/*",
    "requiredSurface": "Searchable localized help articles",
    "sourceSection": "5.1",
    "routeClass": "public_async",
    "ownerMilestone": "M33",
    "journeyIds": [
      "CJ-22"
    ]
  },
  {
    "id": "route.invitations.accept",
    "path": "/invitations/accept",
    "requiredSurface": "Asset-isolated invitation token exchange, preview, and acceptance",
    "sourceSection": "5.1",
    "routeClass": "public_async",
    "ownerMilestone": "M05",
    "journeyIds": [
      "CJ-03"
    ]
  },
  {
    "id": "route.legal.acceptable-use",
    "path": "/legal/acceptable-use",
    "requiredSurface": "Acceptable-use and prohibited-use policy",
    "sourceSection": "5.1",
    "routeClass": "static_public",
    "ownerMilestone": "M33",
    "journeyIds": [
      "CJ-01"
    ]
  },
  {
    "id": "route.legal.dpa",
    "path": "/legal/dpa",
    "requiredSurface": "Data processing terms",
    "sourceSection": "5.1",
    "routeClass": "static_public",
    "ownerMilestone": "M33",
    "journeyIds": [
      "CJ-01"
    ]
  },
  {
    "id": "route.legal.privacy",
    "path": "/legal/privacy",
    "requiredSurface": "Privacy notice",
    "sourceSection": "5.1",
    "routeClass": "static_public",
    "ownerMilestone": "M33",
    "journeyIds": [
      "CJ-01"
    ]
  },
  {
    "id": "route.legal.subprocessors",
    "path": "/legal/subprocessors",
    "requiredSurface": "Current subprocessor list and change process",
    "sourceSection": "5.1",
    "routeClass": "static_public",
    "ownerMilestone": "M33",
    "journeyIds": [
      "CJ-01"
    ]
  },
  {
    "id": "route.legal.terms",
    "path": "/legal/terms",
    "requiredSurface": "Terms of service",
    "sourceSection": "5.1",
    "routeClass": "static_public",
    "ownerMilestone": "M33",
    "journeyIds": [
      "CJ-01"
    ]
  },
  {
    "id": "route.ops",
    "path": "/ops",
    "requiredSurface": "Fleet health, active incidents, SLO burn, deploys, and safe global controls",
    "sourceSection": "5.7",
    "routeClass": "live_operator",
    "ownerMilestone": "M34",
    "journeyIds": [
      "CJ-23"
    ]
  },
  {
    "id": "route.ops.incidents",
    "path": "/ops/incidents",
    "requiredSurface": "Incident lifecycle, roles, timeline, status communication, and post-incident evidence",
    "sourceSection": "5.7",
    "routeClass": "live_operator",
    "ownerMilestone": "M34",
    "journeyIds": [
      "CJ-23"
    ]
  },
  {
    "id": "route.ops.privacy",
    "path": "/ops/privacy",
    "requiredSurface": "Export/delete/hold/retention/residency cases and failed propagation",
    "sourceSection": "5.7",
    "routeClass": "live_operator",
    "ownerMilestone": "M31",
    "journeyIds": [
      "CJ-19"
    ]
  },
  {
    "id": "route.ops.providers",
    "path": "/ops/providers",
    "requiredSurface": "Model/tool/connector/email/billing health, limits, credentials state, and kill switches",
    "sourceSection": "5.7",
    "routeClass": "live_operator",
    "ownerMilestone": "M34",
    "journeyIds": [
      "CJ-23"
    ]
  },
  {
    "id": "route.ops.releases",
    "path": "/ops/releases",
    "requiredSurface": "Artifacts, flags, canaries, migrations, health gates, rollback, and evidence",
    "sourceSection": "5.7",
    "routeClass": "live_operator",
    "ownerMilestone": "M37",
    "journeyIds": [
      "CJ-23.PRODUCTION"
    ]
  },
  {
    "id": "route.ops.runtime",
    "path": "/ops/runtime",
    "requiredSurface": "Queues, Temporal, outbox, stuck work, DLQ, reconciler, and audited repair",
    "sourceSection": "5.7",
    "routeClass": "live_operator",
    "ownerMilestone": "M34",
    "journeyIds": [
      "CJ-23"
    ]
  },
  {
    "id": "route.ops.security",
    "path": "/ops/security",
    "requiredSurface": "Risk events, access review, secret/key/certificate rotation, and break-glass review",
    "sourceSection": "5.7",
    "routeClass": "live_operator",
    "ownerMilestone": "M35",
    "journeyIds": [
      "CJ-23.SECURITY"
    ]
  },
  {
    "id": "route.ops.support",
    "path": "/ops/support",
    "requiredSurface": "Support queues, entitlements, assignment, SLA, and customer-visible messages",
    "sourceSection": "5.7",
    "routeClass": "live_operator",
    "ownerMilestone": "M34",
    "journeyIds": [
      "CJ-23"
    ]
  },
  {
    "id": "route.ops.workspaces.detail",
    "path": "/ops/workspaces/:workspaceId",
    "requiredSurface": "Safe metadata, support-access request/session, throttles, and diagnostics",
    "sourceSection": "5.7",
    "routeClass": "live_operator",
    "ownerMilestone": "M34",
    "journeyIds": [
      "CJ-23"
    ]
  },
  {
    "id": "route.pricing",
    "path": "/pricing",
    "requiredSurface": "Plans, limits, FAQ, enterprise contact",
    "sourceSection": "5.1",
    "routeClass": "static_public",
    "ownerMilestone": "M29",
    "journeyIds": [
      "CJ-01",
      "CJ-17"
    ]
  },
  {
    "id": "route.product",
    "path": "/product",
    "requiredSurface": "Complete product overview",
    "sourceSection": "5.1",
    "routeClass": "static_public",
    "ownerMilestone": "M02",
    "journeyIds": [
      "CJ-01"
    ]
  },
  {
    "id": "route.product.agents",
    "path": "/product/agents",
    "requiredSurface": "Agent foundry and governed execution",
    "sourceSection": "5.1",
    "routeClass": "static_public",
    "ownerMilestone": "M02",
    "journeyIds": [
      "CJ-01"
    ]
  },
  {
    "id": "route.product.integrations",
    "path": "/product/integrations",
    "requiredSurface": "Searchable supported connector catalog",
    "sourceSection": "5.1",
    "routeClass": "public_async",
    "ownerMilestone": "M02",
    "journeyIds": [
      "CJ-01"
    ]
  },
  {
    "id": "route.product.knowledge",
    "path": "/product/knowledge",
    "requiredSurface": "Connected knowledge and provenance",
    "sourceSection": "5.1",
    "routeClass": "static_public",
    "ownerMilestone": "M02",
    "journeyIds": [
      "CJ-01"
    ]
  },
  {
    "id": "route.product.workflows",
    "path": "/product/workflows",
    "requiredSurface": "Workflow studio and runtime",
    "sourceSection": "5.1",
    "routeClass": "static_public",
    "ownerMilestone": "M02",
    "journeyIds": [
      "CJ-01"
    ]
  },
  {
    "id": "route.security",
    "path": "/security",
    "requiredSurface": "Security architecture and controls",
    "sourceSection": "5.1",
    "routeClass": "static_public",
    "ownerMilestone": "M02",
    "journeyIds": [
      "CJ-01"
    ]
  },
  {
    "id": "route.solutions.detail",
    "path": "/solutions/:solution",
    "requiredSurface": "Operations, go-to-market, product, support, finance, HR, IT",
    "sourceSection": "5.1",
    "routeClass": "static_public",
    "ownerMilestone": "M02",
    "journeyIds": [
      "CJ-01"
    ]
  },
  {
    "id": "route.status",
    "path": "/status",
    "requiredSurface": "Link or embedded public status",
    "sourceSection": "5.1",
    "routeClass": "static_public",
    "ownerMilestone": "M33",
    "journeyIds": [
      "CJ-22"
    ]
  },
  {
    "id": "route.templates",
    "path": "/templates",
    "requiredSurface": "Public template gallery",
    "sourceSection": "5.1",
    "routeClass": "public_async",
    "ownerMilestone": "M02",
    "journeyIds": [
      "CJ-01"
    ]
  },
  {
    "id": "route.templates.detail",
    "path": "/templates/:slug",
    "requiredSurface": "Template detail and preview",
    "sourceSection": "5.1",
    "routeClass": "public_async",
    "ownerMilestone": "M02",
    "journeyIds": [
      "CJ-01"
    ]
  },
  {
    "id": "route.trust",
    "path": "/trust",
    "requiredSurface": "Availability, subprocessors, policies, and reports",
    "sourceSection": "5.1",
    "routeClass": "static_public",
    "ownerMilestone": "M33",
    "journeyIds": [
      "CJ-01"
    ]
  }
] as const;
