ALTER TABLE workflow_triggers DROP CONSTRAINT workflow_triggers_kind_check;
ALTER TABLE workflow_triggers ADD CONSTRAINT workflow_triggers_kind_check CHECK(kind IN ('manual','api','signed_webhook','schedule','connector_event','record_created','record_updated','email','message','calendar','file','parent_workflow','webhook','event'));

CREATE TABLE trigger_definition_versions (
 workspace_id uuid NOT NULL,id uuid NOT NULL,trigger_id uuid NOT NULL,version integer NOT NULL,workflow_id uuid NOT NULL,workflow_version integer NOT NULL,trigger_type text NOT NULL,environment text NOT NULL CHECK(environment IN('test','production')),connection_id uuid,schema_version text NOT NULL,filter_expression jsonb NOT NULL DEFAULT '[]',field_mappings jsonb NOT NULL DEFAULT '{}',deduplication_strategy text NOT NULL CHECK(deduplication_strategy IN('event_id','source_sequence','content_window','none_explicit')),concurrency_limit integer NOT NULL CHECK(concurrency_limit>0),rate_per_minute integer NOT NULL CHECK(rate_per_minute>0),configuration jsonb NOT NULL DEFAULT '{}',content_hash text NOT NULL,state text NOT NULL CHECK(state IN('draft','published','superseded')),created_by uuid NOT NULL,created_at timestamptz NOT NULL,PRIMARY KEY(workspace_id,id),UNIQUE(workspace_id,trigger_id,version),FOREIGN KEY(workspace_id,trigger_id) REFERENCES workflow_triggers(workspace_id,id),FOREIGN KEY(workspace_id,workflow_id,workflow_version) REFERENCES workflow_versions(workspace_id,workflow_id,version),FOREIGN KEY(workspace_id,connection_id) REFERENCES connections(workspace_id,id)
);
CREATE TABLE trigger_schedules (
 workspace_id uuid NOT NULL,trigger_version_id uuid NOT NULL,cron_expression text NOT NULL,time_zone text NOT NULL,dst_policy text NOT NULL CHECK(dst_policy IN('skip_gap','next_valid','both_folds','first_fold')),missed_policy text NOT NULL CHECK(missed_policy IN('skip','latest','catch_up')),jitter_seconds integer NOT NULL DEFAULT 0,exclusion_dates date[] NOT NULL DEFAULT '{}',start_at timestamptz,end_at timestamptz,paused_at timestamptz,next_fire_at timestamptz,updated_at timestamptz NOT NULL,PRIMARY KEY(workspace_id,trigger_version_id),FOREIGN KEY(workspace_id,trigger_version_id) REFERENCES trigger_definition_versions(workspace_id,id)
);
CREATE TABLE inbound_event_receipts (
 workspace_id uuid NOT NULL,id uuid NOT NULL,trigger_version_id uuid NOT NULL,connection_id uuid,provider text NOT NULL,source_id text NOT NULL,provider_event_id text,source_sequence bigint,occurred_at timestamptz NOT NULL,received_at timestamptz NOT NULL,schema_version text NOT NULL,payload_hash text NOT NULL,encrypted_payload_reference text NOT NULL,state text NOT NULL CHECK(state IN('accepted','filtered','duplicate','reordered','rejected','queued','started')),normalized_error text,run_id uuid,PRIMARY KEY(workspace_id,id),FOREIGN KEY(workspace_id,trigger_version_id) REFERENCES trigger_definition_versions(workspace_id,id),FOREIGN KEY(workspace_id,connection_id) REFERENCES connections(workspace_id,id)
);
CREATE UNIQUE INDEX inbound_event_provider_dedupe_idx ON inbound_event_receipts(workspace_id,connection_id,provider_event_id) WHERE provider_event_id IS NOT NULL;
CREATE TABLE trigger_source_checkpoints (
 workspace_id uuid NOT NULL,trigger_version_id uuid NOT NULL,source_id text NOT NULL,last_sequence bigint,last_event_at timestamptz,last_receipt_id uuid NOT NULL,reorder_window integer NOT NULL DEFAULT 100,cursor_reference text,updated_at timestamptz NOT NULL,PRIMARY KEY(workspace_id,trigger_version_id,source_id),FOREIGN KEY(workspace_id,trigger_version_id) REFERENCES trigger_definition_versions(workspace_id,id)
);
CREATE TABLE trigger_dispatch_queue (
 workspace_id uuid NOT NULL,id uuid NOT NULL,trigger_version_id uuid NOT NULL,receipt_id uuid NOT NULL,priority integer NOT NULL DEFAULT 100,state text NOT NULL CHECK(state IN('buffered','leased','started','completed','dead_letter')),available_at timestamptz NOT NULL,lease_owner text,lease_expires_at timestamptz,attempt integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL,PRIMARY KEY(workspace_id,id),UNIQUE(workspace_id,receipt_id),FOREIGN KEY(workspace_id,trigger_version_id) REFERENCES trigger_definition_versions(workspace_id,id),FOREIGN KEY(workspace_id,receipt_id) REFERENCES inbound_event_receipts(workspace_id,id)
);
CREATE INDEX trigger_dispatch_fair_queue_idx ON trigger_dispatch_queue(state,available_at,workspace_id,trigger_version_id);
CREATE TABLE trigger_health_snapshots (
 workspace_id uuid NOT NULL,trigger_id uuid NOT NULL,last_received_at timestamptz,last_started_at timestamptz,filtered_count bigint NOT NULL DEFAULT 0,duplicate_count bigint NOT NULL DEFAULT 0,error_count bigint NOT NULL DEFAULT 0,lag_seconds bigint,next_schedule_at timestamptz,disabled_reason text,backlog_count bigint NOT NULL DEFAULT 0,observed_at timestamptz NOT NULL,PRIMARY KEY(workspace_id,trigger_id),FOREIGN KEY(workspace_id,trigger_id) REFERENCES workflow_triggers(workspace_id,id)
);
CREATE TABLE captured_trigger_events (
 workspace_id uuid NOT NULL,id uuid NOT NULL,trigger_version_id uuid NOT NULL,source_receipt_id uuid NOT NULL,capture_environment text NOT NULL CHECK(capture_environment IN('test','production')),redacted_fixture jsonb NOT NULL,payload_hash text NOT NULL,expires_at timestamptz NOT NULL,created_by uuid NOT NULL,created_at timestamptz NOT NULL,PRIMARY KEY(workspace_id,id),FOREIGN KEY(workspace_id,trigger_version_id) REFERENCES trigger_definition_versions(workspace_id,id),FOREIGN KEY(workspace_id,source_receipt_id) REFERENCES inbound_event_receipts(workspace_id,id)
);
CREATE TABLE outbound_sync_lineage (
 workspace_id uuid NOT NULL,id uuid NOT NULL,source_receipt_id uuid NOT NULL,run_id uuid NOT NULL,provider_operation_id uuid NOT NULL,provider_receipt_id uuid,state text NOT NULL CHECK(state IN('pending','approved','uncertain','confirmed','conflict','repaired')),reconciled_at timestamptz,created_at timestamptz NOT NULL,PRIMARY KEY(workspace_id,id),UNIQUE(workspace_id,provider_operation_id),FOREIGN KEY(workspace_id,source_receipt_id) REFERENCES inbound_event_receipts(workspace_id,id),FOREIGN KEY(workspace_id,run_id) REFERENCES workflow_runs(workspace_id,id),FOREIGN KEY(workspace_id,provider_operation_id) REFERENCES provider_action_operations(workspace_id,id),FOREIGN KEY(workspace_id,provider_receipt_id) REFERENCES provider_action_receipts(workspace_id,id)
);
DO $$ DECLARE table_name text; BEGIN FOREACH table_name IN ARRAY ARRAY['trigger_definition_versions','trigger_schedules','inbound_event_receipts','trigger_source_checkpoints','trigger_dispatch_queue','trigger_health_snapshots','captured_trigger_events','outbound_sync_lineage'] LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',table_name);EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',table_name);EXECUTE format('CREATE POLICY %I_tenant ON %I USING (knotline_tenant_visible(workspace_id)) WITH CHECK (knotline_tenant_visible(workspace_id))',table_name,table_name);END LOOP;END $$;
CREATE FUNCTION knotline_trigger_version_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_OP='UPDATE' AND OLD.state='published' AND NEW.state='superseded' AND (to_jsonb(OLD)-'state')=(to_jsonb(NEW)-'state') THEN RETURN NEW; END IF; RAISE EXCEPTION 'trigger versions are immutable' USING ERRCODE='55000'; END $$;
CREATE TRIGGER trigger_definition_versions_immutable BEFORE UPDATE OR DELETE ON trigger_definition_versions FOR EACH ROW EXECUTE FUNCTION knotline_trigger_version_immutable();
CREATE TRIGGER inbound_event_receipts_append_only BEFORE UPDATE OR DELETE ON inbound_event_receipts FOR EACH ROW EXECUTE FUNCTION knotline_append_only();
CREATE TRIGGER captured_trigger_events_append_only BEFORE UPDATE OR DELETE ON captured_trigger_events FOR EACH ROW EXECUTE FUNCTION knotline_append_only();
CREATE TRIGGER outbound_sync_lineage_append_only BEFORE UPDATE OR DELETE ON outbound_sync_lineage FOR EACH ROW EXECUTE FUNCTION knotline_append_only();
REVOKE ALL ON trigger_definition_versions,trigger_schedules,inbound_event_receipts,trigger_source_checkpoints,trigger_dispatch_queue,trigger_health_snapshots,captured_trigger_events,outbound_sync_lineage FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON trigger_schedules,trigger_source_checkpoints,trigger_dispatch_queue,trigger_health_snapshots TO knotline_runtime;
GRANT SELECT,INSERT ON trigger_definition_versions,inbound_event_receipts,captured_trigger_events,outbound_sync_lineage TO knotline_runtime;
GRANT SELECT ON trigger_definition_versions,trigger_schedules,inbound_event_receipts,trigger_source_checkpoints,trigger_dispatch_queue,trigger_health_snapshots,captured_trigger_events,outbound_sync_lineage TO knotline_reporting;
