ALTER TABLE notification_intents DROP CONSTRAINT notification_intents_source_type_check;
ALTER TABLE notification_intents ADD CONSTRAINT notification_intents_source_type_check CHECK(source_type IN('mention','followed_activity','approval_sla','task_assignment','request_changes','sla_warning','sla_breach','run_attention','agent_release','connection_degraded','billing','security','administrator'));
ALTER TABLE notification_intents DROP CONSTRAINT notification_intents_resource_type_check;
ALTER TABLE notification_intents ADD CONSTRAINT notification_intents_resource_type_check CHECK(resource_type IN('workflow','run','task','approval','agent','connection','workspace','billing','security'));
ALTER TABLE notification_intents ADD COLUMN event_type text NOT NULL DEFAULT 'activity.created',ADD COLUMN priority text NOT NULL DEFAULT 'normal' CHECK(priority IN('normal','critical')),ADD COLUMN payload_reference text CHECK(payload_reference IS NULL OR payload_reference LIKE 'encrypted://%'),ADD COLUMN collapse_key text,ADD COLUMN expires_at timestamptz;

CREATE TABLE notification_templates(workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,id uuid NOT NULL,event_type text NOT NULL,channel text NOT NULL CHECK(channel IN('in_app','email','slack','teams','webhook')),locale text NOT NULL DEFAULT 'en',protected boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(workspace_id,id),UNIQUE(workspace_id,event_type,channel,locale));
CREATE TABLE notification_template_versions(workspace_id uuid NOT NULL,id uuid NOT NULL,template_id uuid NOT NULL,version integer NOT NULL CHECK(version>0),variable_schema jsonb NOT NULL CHECK(jsonb_typeof(variable_schema)='object'),subject_template text,body_template text NOT NULL,state text NOT NULL CHECK(state IN('draft','published','superseded')),content_hash text NOT NULL,created_by uuid NOT NULL REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(workspace_id,id),UNIQUE(workspace_id,template_id,version),FOREIGN KEY(workspace_id,template_id) REFERENCES notification_templates(workspace_id,id) ON DELETE CASCADE);
CREATE TABLE notification_preferences(workspace_id uuid NOT NULL,user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,event_type text NOT NULL,channel_cadences jsonb NOT NULL CHECK(jsonb_typeof(channel_cadences)='object'),quiet_start time,quiet_end time,time_zone text NOT NULL,language text NOT NULL DEFAULT 'en',revision integer NOT NULL DEFAULT 1,updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(workspace_id,user_id,event_type));
CREATE TABLE notification_workspace_policies(workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,id uuid NOT NULL DEFAULT gen_random_uuid(),mandatory_events text[] NOT NULL DEFAULT ARRAY['security.account_compromised','security.credential_revoked'],escalation_policy jsonb NOT NULL DEFAULT '{}'::jsonb,rate_limits jsonb NOT NULL DEFAULT '{}'::jsonb,verified_email_domain text,reply_policy text NOT NULL DEFAULT 'no_reply',revision integer NOT NULL DEFAULT 1,updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(workspace_id,id),UNIQUE(workspace_id));
CREATE TABLE notification_items(workspace_id uuid NOT NULL,id uuid NOT NULL,intent_id uuid NOT NULL,recipient_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,group_key text NOT NULL,title text NOT NULL,body_summary text NOT NULL,deep_link text NOT NULL CHECK(deep_link LIKE '/app/%'),resource_auth_epoch bigint NOT NULL DEFAULT 0,read_at timestamptz,unavailable_reason text,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(workspace_id,id),UNIQUE(workspace_id,intent_id,recipient_user_id),FOREIGN KEY(workspace_id,intent_id) REFERENCES notification_intents(workspace_id,id) ON DELETE CASCADE);
CREATE INDEX notification_items_recipient_idx ON notification_items(workspace_id,recipient_user_id,read_at,created_at DESC);
CREATE TABLE notification_deliveries(workspace_id uuid NOT NULL,id uuid NOT NULL,intent_id uuid NOT NULL,recipient_user_id uuid NOT NULL REFERENCES users(id),channel text NOT NULL CHECK(channel IN('in_app','email','slack','teams','webhook')),destination_hash text NOT NULL,idempotency_key text NOT NULL,state text NOT NULL CHECK(state IN('queued','sending','delivered','failed','uncertain','suppressed','dead_lettered')),attempt integer NOT NULL DEFAULT 0,next_attempt_at timestamptz,provider text,provider_receipt_id text,last_error_kind text,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(workspace_id,id),UNIQUE(workspace_id,idempotency_key),FOREIGN KEY(workspace_id,intent_id) REFERENCES notification_intents(workspace_id,id) ON DELETE CASCADE);
CREATE INDEX notification_deliveries_health_idx ON notification_deliveries(workspace_id,channel,state,updated_at DESC);
CREATE TABLE notification_receipts(workspace_id uuid NOT NULL,id uuid NOT NULL,delivery_id uuid NOT NULL,receipt_type text NOT NULL CHECK(receipt_type IN('accepted','delivered','opened','acted','bounced','complained','rejected','reconciled')),provider_receipt_id text,metadata jsonb NOT NULL DEFAULT '{}'::jsonb,received_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(workspace_id,id),FOREIGN KEY(workspace_id,delivery_id) REFERENCES notification_deliveries(workspace_id,id) ON DELETE CASCADE);
CREATE TABLE notification_digests(workspace_id uuid NOT NULL,id uuid NOT NULL,recipient_user_id uuid NOT NULL REFERENCES users(id),cadence text NOT NULL CHECK(cadence IN('daily','weekly')),time_zone text NOT NULL,window_start timestamptz NOT NULL,window_end timestamptz NOT NULL,state text NOT NULL CHECK(state IN('building','ready','delivered','suppressed')),authorization_checked_at timestamptz,membership jsonb NOT NULL DEFAULT '[]'::jsonb,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(workspace_id,id),UNIQUE(workspace_id,recipient_user_id,cadence,window_start));
CREATE TABLE notification_suppressions(workspace_id uuid NOT NULL,id uuid NOT NULL,recipient_user_id uuid,event_type text,channel text,reason text NOT NULL CHECK(reason IN('preference','quiet_hours','invalid_target','bounce','complaint','rate_limit','circuit_open','authorization_revoked','resource_deleted','duplicate')),expires_at timestamptz,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(workspace_id,id));
CREATE TABLE notification_channel_installations(workspace_id uuid NOT NULL,id uuid NOT NULL,channel text NOT NULL CHECK(channel IN('email','slack','teams','webhook')),connection_id uuid,secret_reference text CHECK(secret_reference IS NULL OR secret_reference LIKE 'secret://%'),configuration jsonb NOT NULL DEFAULT '{}'::jsonb,state text NOT NULL CHECK(state IN('active','degraded','disabled')),external_gate text,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(workspace_id,id));

CREATE FUNCTION knotline_notification_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'notification evidence is immutable' USING ERRCODE='55000'; END $$;
CREATE TRIGGER notification_template_versions_immutable BEFORE UPDATE OR DELETE ON notification_template_versions FOR EACH ROW EXECUTE FUNCTION knotline_notification_immutable();
CREATE TRIGGER notification_receipts_immutable BEFORE UPDATE OR DELETE ON notification_receipts FOR EACH ROW EXECUTE FUNCTION knotline_notification_immutable();
DO $$ DECLARE table_name text; BEGIN FOREACH table_name IN ARRAY ARRAY['notification_templates','notification_template_versions','notification_preferences','notification_workspace_policies','notification_items','notification_deliveries','notification_receipts','notification_digests','notification_suppressions','notification_channel_installations'] LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',table_name);EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',table_name);EXECUTE format('CREATE POLICY %I_tenant ON %I USING (knotline_tenant_visible(workspace_id)) WITH CHECK (knotline_tenant_visible(workspace_id))',table_name,table_name);END LOOP;END $$;
REVOKE ALL ON notification_templates,notification_template_versions,notification_preferences,notification_workspace_policies,notification_items,notification_deliveries,notification_receipts,notification_digests,notification_suppressions,notification_channel_installations FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON notification_templates,notification_preferences,notification_workspace_policies,notification_items,notification_deliveries,notification_digests,notification_suppressions,notification_channel_installations TO knotline_runtime;
GRANT SELECT,INSERT ON notification_template_versions,notification_receipts TO knotline_runtime;
GRANT SELECT ON notification_templates,notification_template_versions,notification_preferences,notification_workspace_policies,notification_items,notification_deliveries,notification_receipts,notification_digests,notification_suppressions,notification_channel_installations TO knotline_reporting;
GRANT EXECUTE ON FUNCTION knotline_notification_immutable() TO knotline_runtime,knotline_reporting,knotline_repair;
